Anisha add retinanet test
GoogleCloudPlatform/ml-testing-accelerators pull request #641
Opened 2022-05-20 18:47 UTC by A9isha

Add TF `vision-retinanet` test

2022-05-20 20:50 UTC, will-cromar requested changes

2022-05-20 20:50 UTC, will-cromar commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +	    global_batch_size: 64,
Add this to `v2_8` instead:

```
      paramsOverride+: {
        task: {
          train_data: {
	    global_batch_size: 64,
          },
        },
      },
```

This way, the batch size change takes effect for both the functional and convergence tests, and you don't have to have two copies of `functional`.

2022-05-20 20:50 UTC, will-cromar commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +        task: {
Move these common fields to `retinanet` instead:

```
      paramsOverride+: {
        task: {
          annotation_file: '$(COCO_DIR)/instances_val2017.json',
	  train_data: {
            input_path: '$(COCO_DIR)/train*',
          },
	  validation_data: {
            input_path: '$(COCO_DIR)/val*',
          },
        },
```

The input data is common to both `functional` and `convergence`, but right now the convergence test doesn't point to any input data.

2022-05-20 20:50 UTC, will-cromar commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +    PreemptibleTpu:: {
Remove this `PreemptibleTpu` block. It probably doesn't do what you want it to, and we want to control TPU preemptibility in common templates.

2022-05-23 15:42 UTC, will-cromar requested changes
Otherwise LGTM

2022-05-23 15:42 UTC, will-cromar commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +// Copyright 2021 Google LLC
2022

2022-05-23 15:42 UTC, will-cromar commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +            global_batch_size: 32,
I would create a common TPU subclass where you compute the validation batch size according to the number of replicas (i.e. `config.accelerator.replicas`). See this example:

https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/7dec2008823f97ec67a4ab444a8975d4aa2e1ad2/tests/tensorflow/r2.8/maskrcnn.libsonnet#L91-L93

2022-05-23 19:40 UTC, will-cromar commented
Can you also rename this file `vision-coco` to align with `vision-imagenet`? We may want to add more tests that use the same dataset

2022-05-26 19:25 UTC, A9isha commented on tests/tensorflow/nightly/vision-retinanet.libsonnet
> +// Copyright 2021 Google LLC
done

2022-05-26 20:06 UTC, will-cromar approved these changes
LGTM. Great work!

2022-05-26 20:55 UTC, merged